default: &default
  external_video_hosting: false
  sidekiq_auth_enabled: false
  enable_chatwoot: false

production:
  <<: *default
  external_video_hosting: true
  sidekiq_auth_enabled: true

staging:
  <<: *default
  external_video_hosting: true
  sidekiq_auth_enabled: true
  enable_chatwoot: true

development:
  <<: *default

test:
  <<: *default

docker:
  <<: *default
